### ISSUE TITLE
GPU farming on Nvidia only?

### ISSUE THREAD

**Issue by heichwald** [madMAx43v3r/chia-gigahorse#1]
Hello Max,

thanks for the awesome work.
I just wanted to ask as it seems that plotting needs cuda and Nvidia GPU.
Is it the same for farming? or does Amd work too there?
If Nvidia only, is it the same as for plotting in regards to generations gtx 1xxx and above?

Thank you

**Comment by madMAx43v3r** [comment]
Yeah currently it's the same for farming, support starting at CC 5.2, which is Maxwell 2.0 like K2200.
