### ISSUE TITLE
plot copy tool often fails

### ISSUE THREAD

**Issue by mmitech** [madMAx43v3r/chia-gigahorse#10]
The plot copy tool fails all the time with this errors : 
`send() failed with: Success (0)`  
`connect() failed with: Network is unreachable (101)`

![image](https://user-images.githubusercontent.com/4456920/218302143-334aaef8-e28d-40c6-952b-21fec5a2068d.png)

on the receiving side:

![image](https://user-images.githubusercontent.com/4456920/218302347-1fa7eb25-975f-44a2-b84e-6e9535bfda19.png)

then the files are deleted.

After it successfully copies a few plots it does it for the rest of the plots, I thought it might be a network issue but I tried a different NIC and switch with the same results I also tried https://github.com/maxbanton/chia-plot-mover and it doesn't seem to have these issues.

I would rather use the plot sync-copy tool since it seems way faster than the plot mover.

Edit: add more info

**Comment by madMAx43v3r** [comment]
![image](https://user-images.githubusercontent.com/951738/218339688-bb0f34d9-0c77-45c6-aead-7b67989b83ee.png)

I'm doing blocking send() call, if that fails, it's gotta be something with the network...
It looks like someone is terminating the connections..

**Comment by mmitech** [comment]
Yes, it was the 40G copper cable, I changed it and now it is working just fine.
