### ISSUE TITLE
Windows Defender dislikes 1.8.0.giga11

### ISSUE THREAD

**Issue by AtomicInternet2** [madMAx43v3r/chia-gigahorse#119]
Please feel free to delete this if it's a known issue.  I also realize you have little to no control over what Defender decides is good or bad software.  I'm mostly posting this for awareness as my farm stopped after Defender decided giga11 was no good and I was down for a few hours.  If anyone else reads these and farms with giga11 on Windows 11 check your farm status.

Defender will aggressively block chia.exe from the 1.8.0.giga11 release version in Windows 11.  It does not seem to have issue with 1.8.0.giga10.  This seems to have happened in a recent update as I was running giga11 with no problem for the last 2 days.

**Comment by madMAx43v3r** [comment]
Hmm maybe the new remote compute feature?

**Comment by Drhicom** [comment]
Did you try 1.8.2.giga14 ?

**Comment by AtomicInternet2** [comment]
I'm all set, added the entire Gigahorse directory to my windows defender exclusions.  I mostly put this here in case anyone else was having the same mystery.  I'll close it.
