### ISSUE TITLE
3080显卡512G内存绘图P1阶段

### ISSUE THREAD

**Issue by outlixs** [madMAx43v3r/chia-gigahorse#123]
3080显卡512G内存绘图P1阶段自动停止，请问是哪里出错，谢谢
![308011](https://github.com/madMAx43v3r/chia-gigahorse/assets/133863069/84f90f91-b842-470f-b7c5-b89b2fd43888)
![Uploading 308011.png…]()

**Comment by Block-Captain** [comment]
Shall be a bug in Win, try "-M 99" or "-M 70" ? Better to use Ubuntu linux.

**Comment by madMAx43v3r** [comment]
need `-M 128` in windows for 256G RAM mode

**Comment by Block-Captain** [comment]
> 可以了，谢谢您，再问一下，显卡p的压缩图，需要什么配置的收割机才能挂300-500t的压缩图

It depends on your compression level and the filter number of the project, see the table in the README of this repository, a 3060 Ti can handle 1.78P C8 plots for MMX or currently double for XCH.

This issue can be closed.
