### ISSUE TITLE
Cannot open at least 576 files, please raise maximum open file limit in OS.

### ISSUE THREAD

**Issue by MrMrRubic** [madMAx43v3r/chia-gigahorse#125]
### **What happened?**
When trying to use: `chia_plot.exe -r 16 -u 512 -v 256 -K 2 -C 5 -n 1...` I'm seeing the following error message:  `Cannot open at least 576 files, please raise maximum open file limit in OS.`

when lowering the bucket count back to the default 256 the problem stops. The higher bucket count have worked flawlessly when i was plotting regular plots with madmax-plotter last year.

My server has 128gb ram, of which 110g is used for ramdisk.

This is essentially the same problem as [Chia-Network/chia-blockchain#13741](https://github.com/Chia-Network/chia-blockchain/issues/13741) but on windows instead of MacOS, with the addition of me not having any idea how to increase the maximum file limit.
### **Version**
Gigahorse CPU-plotter v2.0.0-16eca1f

### **What platform are you using?**
Windows server 2019, with all the latest updates

### **What ui mode are you using?**
CLI

### **Relevant log output**
`Cannot open at least 576 files, please raise maximum open file limit in OS.`

**Comment by madMAx43v3r** [comment]
Try latest version, I added code for windows to increase max open limit.

**Comment by MrMrRubic** [comment]
Thank you, that seems to have resolved the issue.
