### ISSUE TITLE
Will the 3060Ti LHR version have an effect on plotter and farming ?

### ISSUE THREAD

**Issue by TianciD** [madMAx43v3r/chia-gigahorse#126]
This will affect my next plan

**Comment by TianciD** [comment]
This will affect my next plan

**Comment by Block-Captain** [comment]
Tested 3060 LHR, which works normally

**Comment by madMAx43v3r** [comment]
LHR cards work fine yes, I used to have a 3060 LHR when developing the plotter ;)
