### ISSUE TITLE
Is it possible to plot on an ARM CPU?

### ISSUE THREAD

**Issue by x1957** [madMAx43v3r/chia-gigahorse#130]
I don't care much about the speed of plotting, just need the compression ratio.

**Comment by madMAx43v3r** [comment]
I can make a binary for it yes

**Comment by madMAx43v3r** [comment]
Check https://github.com/madMAx43v3r/chia-gigahorse/tree/master/cpu-plotter/linux/arm64

**Comment by x1957** [comment]
thanks!

**Comment by x1957** [comment]
I tried using glibc version 2.30, but I'm experiencing a Segmentation fault during runtime. If I use other versions of glibc, I encounter a 'symbol not defined' problem. Could you possibly compile a version using the -static flag?

**Comment by madMAx43v3r** [comment]
Pretty sure that's not possible, a lot going on to compile this.

What distro you using?

**Comment by madMAx43v3r** [comment]
I'm compiling on Ubuntu 20.04, so it should work on anything after that.

**Comment by x1957** [comment]
CentOS Linux release 7.9.2009 (AltArch)

**Comment by madMAx43v3r** [comment]
Ouch, that's very old ... I wont be able to compile on anything older than 20.04

**Comment by x1957** [comment]
Thanks, I will think about other methods.

**Comment by x1957** [comment]
@madMAx43v3r  Thank you very much for your help. I have tested the ARM version, and the farm is slightly slower. We plan to install a few graphics cards. Can you provide an ARM version of the GPU plot binary? 
Thanks

**Comment by madMAx43v3r** [comment]
GPU plotter only supports Nvidia, and Nvidia typically don't support ARM unless it's a Jetson

**Comment by madMAx43v3r** [comment]
Apart from Jetson they only support `arm64-sbsa`, so it depends what kind of system you are talking about.

**Comment by x1957** [comment]
Thanks, I checked, and my CPU supports SBSA.

**Comment by madMAx43v3r** [comment]
Can you check if it supports CUDA? Try to install nvidia drivers and run some CUDA benchmarks.

**Comment by x1957** [comment]
OK, I will check this in a few days.

**Comment by x1957** [comment]
Thanks, We are using x84 plotting now
