### ISSUE TITLE
can set per GPU weight for Remote Compute ?

### ISSUE THREAD

**Issue by sxwailyc** [madMAx43v3r/chia-gigahorse#132]
can set per GPU weight for Remote Compute ? 

My current issue is that when I use an RTX 3080 and a P102 together, the load on the 3080 is very low, but the load on the P106 is very high.

**Comment by madMAx43v3r** [comment]
You can specify the same host multiple times, but P102 is heavily bottlenecked by PCIe 1.0, should not use it at all.

**Comment by sxwailyc** [comment]
I see, tks
