### ISSUE TITLE
Starting farmer error on Win 10

### ISSUE THREAD

**Issue by aeugene1977** [madMAx43v3r/chia-gigahorse#133]
Hi, I have a problem with running the farmer from the command line on Windows 10 Pro. Before that, I used the Chia application while the plots were not compressed. Now I have transferred some of them to the C8 level using Madmax Gigahorse (version 1.8.1) . When I start farming , the following is issued:
‘’’
PS C:\chia-gigahorse-farmer> ./chia start farmer
Daemon not started yet
Starting daemon
Traceback (most recent call last):
File “C:\CHIA-G~1\chia.py”, line 4, in
File “”, line 1027, in _find_and_load
File “”, line 1006, in _find_and_load_unlocked
File “”, line 688, in _load_unlocked
File “C:\CHIA-G~1\chia.py”, line 139, in
File “C:\CHIA-G~1\chia.py”, line 135, in main
File “C:\CHIA-G~1\click\core.py”, line 1130, in call
File “C:\CHIA-G~1\click\core.py”, line 1055, in main
File “C:\CHIA-G~1\click\core.py”, line 1657, in invoke
File “C:\CHIA-G~1\click\core.py”, line 1404, in invoke
File “C:\CHIA-G~1\click\core.py”, line 760, in invoke
File “C:\CHIA-G~1\click\decorators.py”, line 26, in new_func
File “C:\CHIA-G~1\chia\cmds\start.py”, line 23, in start_cmd
File “C:\CHIA-G~1\asyncio\runners.py”, line 44, in run
File “C:\CHIA-G~1\asyncio\base_events.py”, line 649, in run_until_complete
File “C:\CHIA-G~1\chia\cmds\start_funcs.py”, line 64, in async_start
File “C:\CHIA-G~1\chia\cmds\start_funcs.py”, line 42, in create_start_daemon_connection
File “codecs.py”, line 322, in decode
UnicodeDecodeError: ‘utf-8’ codec can’t decode byte 0xc5 in position 29: invalid continuation byte
PS C:\chia-gigahorse-farmer>
‘’’
Before that, I ran the Gigahorse farmer on two nodes in this way and there were never any errors. What could be the reason?

**Comment by madMAx43v3r** [comment]
It seems you are mixing official Node with Gigahorse Farmer, cannot do that. Need to run Gigahorse Node also. Make sure to restart properly via `chia stop all -d`. The `-d` is important.

**Comment by madMAx43v3r** [comment]
It just seems there is still some official Chia daemon running. Can you just reboot to make sure?

**Comment by madMAx43v3r** [comment]
In any case, you need to use `chia.exe start farmer`.

**Comment by zhurakovsky01** [comment]
> Привет, у меня проблема с запуском фермера из командной строки в Windows 10 Pro. До этого пользовался приложением Chia пока графики не сжимались. Сейчас я перевел часть из них на уровень С8 с помощью Madmax Gigahorse (версия 1.8.1). Когда я запускаю ферму, выдается следующее: ''' PS C:\chia-gigahorse-farmer> ./chia start farmer Демон еще не запущен Запуск демона Traceback (последний вызов): Файл «C:\CHIA-G~1\chia.py», строка 4, в файле «», строка 1027, в файле _find_and_load «», строка 1006, в файле _find_and_load_unlocked «», строка 688, в файле _load_unlocked «C:\CHIA-G~1\chia.py», строка 139, в файле «C:\CHIA-G~1\chia.py», строка 135, в основном файле «C:\CHIA-G~1\click\core.py», строка 1130, в файле вызова «C:\CHIA-G~1\click\core.py», строка 1055, в основном файле «C:\CHIA-G~1\click\core.py», строка 1657, в файле вызова «C:\CHIA-G~1\click\core.py», строка 1404, в файле вызова «C:\CHIA-G~1\click\core.py», строка 760, в файле вызова «C:\CHIA-G~1\click\decorators.py», строка 26, в файле new_func «C:\CHIA-G~1\chia\cmds\start.py», строка 23, в файле start_cmd «C:\CHIA-G~1\asyncio\runners.py», строка 44, в файле запуска «C:\CHIA-G~1\asyncio\base_events.py», строка 649, в файле run_until_complete «C:\CHIA-G~1\chia\cmds\start_funcs.py», строка 64, в файле async_start «C:\CHIA-G~1\chia\cmds\start_funcs.py", строка 42, в файле create_start_daemon_connection "codecs.py", строка 322, при декодировании UnicodeDecodeError: кодек 'utf-8' не может декодировать байт 0xc5 в позиции 29: неверный байт продолжения PS C:\chia-gigahorse-farmer> ''' До этого я запускал Gigahorse farmer на двух нодах таким образом и ни разу не было ошибок. Что может быть причиной?
Запустите повторно start_farmer.cmd. Со второго раза запустится. Проблема в том, что у вас имя юзера виндовс на кирилице. Измените ПРАВИЛЬНО имя юзера виндовс на латиницу и все пройдет.

**Comment by aeugene1977** [comment]
> Запустите повторно start_farmer.cmd. Со второго раза запустится. Проблема в том, что у вас имя юзера виндовс на кирилице. Измените ПРАВИЛЬНО имя юзера виндовс на латиницу и все пройдет.

Спасибо, я уже вчера сам догадался)
