### ISSUE TITLE
Is the plot bad?

### ISSUE THREAD

**Issue by zhurakovsky01** [madMAx43v3r/chia-gigahorse#163]
@madMAx43v3r 
![photo_2023-06-25_16-34-34](https://github.com/madMAx43v3r/chia-gigahorse/assets/63637163/2e8ce376-e233-42a0-9037-1d994d8e6109)
Who to believe? Is this plot bad or is it a glitch when farming?

**Comment by madMAx43v3r** [comment]
It's a glitch

**Comment by zhurakovsky01** [comment]
> It's a glitch

Thank you very much for the answer. Ah, then I removed such plots and redid it again (
