### ISSUE TITLE
ERROR using prover object could not resolve: 'CHIAPOS_RECOMPUTE_HOST=...'

### ISSUE THREAD

**Issue by FarmingKid** [madMAx43v3r/chia-gigahorse#178]
I set up the Recompute Setup and on my harvester I get in the Logs this message:
2023-08-01T10:21:02.599 harvester chia.harvester.harvester: ERROR    Error using prover object could not resolve: 'CHIAPOS_RECOMPUTE_HOST=...'

What should I do here?

**Comment by madMAx43v3r** [comment]
You made a mistake when setting the variable, can you show what you did?

**Comment by FarmingKid** [comment]
![image](https://github.com/madMAx43v3r/chia-gigahorse/assets/80603545/3e25b9cd-eafa-43f4-94fd-6a0b56edde7b)

**Comment by madMAx43v3r** [comment]
Hmm looks correct. Did you try restart or new terminal?

**Comment by FarmingKid** [comment]
sometimes the simple things were the best way :) I started a new Terminal and now everything works without error.
thx for help
