### ISSUE TITLE
<class 'asyncio.exceptions.TimeoutError'>, closing connection PeerInfo(_ip=IPv4Address('127.0.0.1'), _port=8447)

### ISSUE THREAD

**Issue by leeivan** [madMAx43v3r/chia-gigahorse#185]
<class 'asyncio.exceptions.TimeoutError'>, closing connection PeerInfo(_ip=IPv4Address('127.0.0.1'), _port=8447)

**Comment by zhurakovsky01** [comment]
time synced on your PC?

**Comment by leeivan** [comment]
Yes, I used ubuntu.
System clock synchronized: yes

**Comment by madMAx43v3r** [comment]
that's normal
