### ISSUE TITLE
Gigahorse 15

### ISSUE THREAD

**Issue by Kruger1981** [madMAx43v3r/chia-gigahorse#198]
@madMAx43v3r 
Any predictions as to when the next Gigahorse version to support Chia 2.0.0 GUI on Windows will come out?

**Comment by endurance1968** [comment]
this seems to be the same as https://github.com/madMAx43v3r/chia-gigahorse/issues/193

**Comment by madMAx43v3r** [comment]
Depends on demand, lets see how quick 2.1 comes out

**Comment by Kruger1981** [comment]
Cool, thank you for the heads up.
2.0.0 has some fancy stats on farmer and harvester GUI that can be useful 😃

**Comment by endurance1968** [comment]
> Cool, thank you for the heads up. 2.0.0 has some fancy stats on farmer and harvester GUI that can be useful 😃

I agree the frontend has improved a lot.

**Comment by Kruger1981** [comment]
Would be cool to have this working.
(I do like my stats and graphs LOL)
