### ISSUE TITLE
FileStore: write('/mnt/local/cuda_plot_tmp2_1695054999750662.tmp') failed with: Structure needs cleaning

### ISSUE THREAD

**Issue by Mathis436** [madMAx43v3r/chia-gigahorse#208]
Working Directory:   /mnt/temp/
Working Directory 2: /mnt/local/
Compression Level: C8 (xbits = 8, final table = 4)
Plot Name: plot-k32-c8-2023-09-18-16-36-583503acf64bf0c25d2f50ba50d33c4a7e03a99b37c7b21ae01df785459784d0
Created disk buffer /mnt/local/cuda_plot_tmp2_1695054999750662.tmp
[P1] Setup took 0.707 sec
[P1] Table 1 took 85.795 sec, 4294967296 entries, 16789222 max, 66622 tmp, 0 GB/s up, 0.396296 GB/s down
[P1] Table 2 took 86.778 sec, 4294839248 entries, 16789540 max, 66587 tmp, 0.368757 GB/s up, 0.587709 GB/s down
[P1] Table 3 took 99.837 sec, 4294624454 entries, 16788671 max, 66617 tmp, 0.480769 GB/s up, 0.85139 GB/s down
FileStore: write('/mnt/local/cuda_plot_tmp2_1695054999750662.tmp') failed with: Structure needs cleaning
[P1] Table 4 took 102.703 sec, 4294190898 entries, 16785874 max, 66619 tmp, 0.778883 GB/s up, 1.15868 GB/s down
FileStore: write('/mnt/local/cuda_plot_tmp2_1695054999750662.tmp') failed with: Structure needs cleaning

this is a 1/2 ram GPU plotter. any ideas?

**Comment by Kruger1981** [comment]
Seems to me that its a Linux issue not the gigahorse.

If you are using a NVME or SSD to plot may indicate that its about to die.

Can you test plotting on a different drive?

**Comment by Kruger1981** [comment]
Test formatting the drive, reboot and plot to see if the issue persists.

**Comment by Mathis436** [comment]
Trying that now. Ill report back if any thing changes.

**Comment by Mathis436** [comment]
I tried a reformat, reboot, and overnight plotting and all is fine!
