### ISSUE TITLE
Wrong destination drives used if chia_plot_sink_disable is used / cuda-plotter

### ISSUE THREAD

**Issue by Jacek-ghub** [madMAx43v3r/chia-gigahorse#21]
cuda-ploter is using a round-robin for plot distribution.  It works great if there is room on all destination drives, or some are already full.  

However, when a drive is blocked by chia_plot_sink_disable, such destination is skipped, but the index is not advanced appropriately, thus the next destination drive is using (n+1) plots (n - number of drives in the row blocked by sink-disable.

Maybe a test for that file should be added to the same function that does checks for space availability, as that flow is working fine.

**Comment by madMAx43v3r** [comment]
I'd have to sort by free space to fix that.

**Comment by Jacek-ghub** [comment]
What if that is treated as equivalent to "disk full"?  The disk full works fine right now (I think, didn't have problems with it so far, but don't have that condition too often), so maybe just a wrapper over disk-full-test that will check both conditions will be simpler?

What I see in my case (d1-d5) when I blocked d2/3, the plot distribution was d1, d4, d4, d4, d5.  

Although, I run the plotter without the final xfr.  I have -t /nvme, -d /nvme/d1, -d /nvme/d2, ...  where all those d1-d6 are just subfolders on the /nvme drive.  I run respective shell scripts to pick those files from those d1-d5 folders and move them to HDs.  This way (it looks to me) the plot times are more consistent and shorter.

**Comment by madMAx43v3r** [comment]
[cuda_plot_even_hdd_fill_test.zip](https://github.com/madMAx43v3r/chia-gigahorse/files/10808809/cuda_plot_even_hdd_fill_test.zip)

Try this version, should fill them equally.

**Comment by Jacek-ghub** [comment]
It doesn't.  

At the end of the first round, I blocked d3/4.  In both 2nd and 3rd run d5 got 3 plots.

k32 / C7 / bf20709
```
Started copy to /mnt/nvme/mmx/tmp1/d1/plot-mmx-k32-c7-2023-02-22-14-44-74be0d9479fc43f5f089bfe998bdf298b0b36e927af764264b7e95a8fe0fcfaa.plot
Renamed final plot to /mnt/nvme/mmx/tmp1/d1/plot-mmx-k32-c7-2023-02-22-14-44-74be0d9479fc43f5f089bfe998bdf298b0b36e927af764264b7e95a8fe0fcfaa.plot
Started copy to /mnt/nvme/mmx/tmp1/d2/plot-mmx-k32-c7-2023-02-22-14-48-5ca9db3f15de920d221648f3ef734bace9c99067f6fcba8061b77819d8f32e62.plot
Renamed final plot to /mnt/nvme/mmx/tmp1/d2/plot-mmx-k32-c7-2023-02-22-14-48-5ca9db3f15de920d221648f3ef734bace9c99067f6fcba8061b77819d8f32e62.plot
Started copy to /mnt/nvme/mmx/tmp1/d3/plot-mmx-k32-c7-2023-02-22-14-51-1765ca659ad7a4caba1b3f9cc84f37f2bc7909bd543651299e547fd9036def63.plot
Renamed final plot to /mnt/nvme/mmx/tmp1/d3/plot-mmx-k32-c7-2023-02-22-14-51-1765ca659ad7a4caba1b3f9cc84f37f2bc7909bd543651299e547fd9036def63.plot
Started copy to /mnt/nvme/mmx/tmp1/d4/plot-mmx-k32-c7-2023-02-22-14-53-8ccef01b822db114d742c357aa7ec93b1098371f07712f004425ce91bd7384c4.plot
Renamed final plot to /mnt/nvme/mmx/tmp1/d4/plot-mmx-k32-c7-2023-02-22-14-53-8ccef01b822db114d742c357aa7ec93b1098371f07712f004425ce91bd7384c4.plot
Started copy to /mnt/nvme/mmx/tmp1/d5/plot-mmx-k32-c7-2023-02-22-14-56-49876f7eafea6a663911c262a778ddcdd7758150a02c7cbe074a8738a4e7ed5b.plot
Renamed final plot to /mnt/nvme/mmx/tmp1/d5/plot-mmx-k32-c7-2023-02-22-14-56-49876f7eafea6a663911c262a778ddcdd7758150a02c7cbe074a8738a4e7ed5b.plot
Started copy to /mnt/nvme/mmx/tmp1/d6/plot-mmx-k32-c7-2023-02-22-14-58-7c543227fbc0efb8547e036afd088cda0a03ea52c4900923021a9b3535839414.plot
Renamed final plot to /mnt/nvme/mmx/tmp1/d6/plot-mmx-k32-c7-2023-02-22-14-58-7c543227fbc0efb8547e036afd088cda0a03ea52c4900923021a9b3535839414.plot
Started copy to /mnt/nvme/mmx/tmp1/d1/plot-mmx-k32-c7-2023-02-22-15-01-22b44b58227247a4985ec1ed9c865d9dd976f49975f3273b96e439df7d138205.plot
Renamed final plot to /mnt/nvme/mmx/tmp1/d1/plot-mmx-k32-c7-2023-02-22-15-01-22b44b58227247a4985ec1ed9c865d9dd976f49975f3273b96e439df7d138205.plot
Started copy to /mnt/nvme/mmx/tmp1/d2/plot-mmx-k32-c7-2023-02-22-15-03-4ce9b32e174bb36c1cea9049fdadc0173ac73d26b8e3d9dfae5c446e6fd60ef7.plot
Renamed final plot to /mnt/nvme/mmx/tmp1/d2/plot-mmx-k32-c7-2023-02-22-15-03-4ce9b32e174bb36c1cea9049fdadc0173ac73d26b8e3d9dfae5c446e6fd60ef7.plot
  Started copy to /mnt/nvme/mmx/tmp1/d5/plot-mmx-k32-c7-2023-02-22-15-06-6d1793583f33bb4d99e8289d6363d9816ab5365623f4186f2a561d97586bf744.plot
  Renamed final plot to /mnt/nvme/mmx/tmp1/d5/plot-mmx-k32-c7-2023-02-22-15-06-6d1793583f33bb4d99e8289d6363d9816ab5365623f4186f2a561d97586bf744.plot
  Started copy to /mnt/nvme/mmx/tmp1/d5/plot-mmx-k32-c7-2023-02-22-15-08-fa18850cf525756507d5ef6526e8952f7e4bbbdff9f278ac19c6f8ffbbb63cff.plot
  Renamed final plot to /mnt/nvme/mmx/tmp1/d5/plot-mmx-k32-c7-2023-02-22-15-08-fa18850cf525756507d5ef6526e8952f7e4bbbdff9f278ac19c6f8ffbbb63cff.plot
  Started copy to /mnt/nvme/mmx/tmp1/d5/plot-mmx-k32-c7-2023-02-22-15-11-3440d2ba0074e7ea43b0fa2557df42c6d473707412bd1ffac920f10c0e173cd7.plot
  Renamed final plot to /mnt/nvme/mmx/tmp1/d5/plot-mmx-k32-c7-2023-02-22-15-11-3440d2ba0074e7ea43b0fa2557df42c6d473707412bd1ffac920f10c0e173cd7.plot
Started copy to /mnt/nvme/mmx/tmp1/d6/plot-mmx-k32-c7-2023-02-22-15-13-257b6fdc8c4b9931414bf7a314b80445aa3f1e8b95b06e8db2379a8ccda0e45d.plot
Renamed final plot to /mnt/nvme/mmx/tmp1/d6/plot-mmx-k32-c7-2023-02-22-15-13-257b6fdc8c4b9931414bf7a314b80445aa3f1e8b95b06e8db2379a8ccda0e45d.plot
Started copy to /mnt/nvme/mmx/tmp1/d1/plot-mmx-k32-c7-2023-02-22-15-16-e1927ab5076e87a01d24359a2d40894e7288e8b5b60a80eb525efa97d0e004b3.plot
Renamed final plot to /mnt/nvme/mmx/tmp1/d1/plot-mmx-k32-c7-2023-02-22-15-16-e1927ab5076e87a01d24359a2d40894e7288e8b5b60a80eb525efa97d0e004b3.plot
Started copy to /mnt/nvme/mmx/tmp1/d2/plot-mmx-k32-c7-2023-02-22-15-18-1f3dbdee625b553d405a93d8d6989165684557124169f31771c1dadcb0f6eb51.plot
Renamed final plot to /mnt/nvme/mmx/tmp1/d2/plot-mmx-k32-c7-2023-02-22-15-18-1f3dbdee625b553d405a93d8d6989165684557124169f31771c1dadcb0f6eb51.plot
  Started copy to /mnt/nvme/mmx/tmp1/d5/plot-mmx-k32-c7-2023-02-22-15-21-1e83fcc6276f2bee5192c280b93f7d4f881b0448cf15d048af86a28826399df8.plot
  Renamed final plot to /mnt/nvme/mmx/tmp1/d5/plot-mmx-k32-c7-2023-02-22-15-21-1e83fcc6276f2bee5192c280b93f7d4f881b0448cf15d048af86a28826399df8.plot
  Started copy to /mnt/nvme/mmx/tmp1/d5/plot-mmx-k32-c7-2023-02-22-15-24-9b83f3e6abbe57a01d0eac52c3ef6f63f26c14c81bb22f6c965b8c9df3754e2a.plot
  Renamed final plot to /mnt/nvme/mmx/tmp1/d5/plot-mmx-k32-c7-2023-02-22-15-24-9b83f3e6abbe57a01d0eac52c3ef6f63f26c14c81bb22f6c965b8c9df3754e2a.plot
  Started copy to /mnt/nvme/mmx/tmp1/d5/plot-mmx-k32-c7-2023-02-22-15-26-7b9d208aed323ce1613a75f68f20d79c604bf7825725c893979e35601315ecd0.plot
  Renamed final plot to /mnt/nvme/mmx/tmp1/d5/plot-mmx-k32-c7-2023-02-22-15-26-7b9d208aed323ce1613a75f68f20d79c604bf7825725c893979e35601315ecd0.plot
```

**Comment by madMAx43v3r** [comment]
Ah, because it's the same physical drive, all the folders have the same "free space", so my improved sorting wont work...

**Comment by Jacek-ghub** [comment]
That's what I was trying to tell.  Therefore, I suggested that it should be part of "not enough room" rather than a separate check.

**Comment by madMAx43v3r** [comment]
But there is enough room, with your config all the `-d` have the same free space, so to the plotter it doesnt matter which it should pick next. I would have to track how many plots have been written already to each folder, but that wont work once you remount new drives on the same paths.

**Comment by madMAx43v3r** [comment]
If you plot directly to the HDDs now, with this test version it should work.

**Comment by madMAx43v3r** [comment]
There's many ways to code the algorithm to pick the next drive, but the optimal solution for your current case will not be optimal for most users...

**Comment by Jacek-ghub** [comment]
> so to the plotter it doesnt matter which it should pick next

That's not how I understand round-robin, so that maybe is part of my confusion.  For round-robin, there is no extra sorting, just going by index.  Thus skipping a destination due to a given target being full implies advancing the rr index.  That's why I was saying that the blocking file should be equivalent to disk full.

**Comment by madMAx43v3r** [comment]
It was round robin in the beginning, but it's not anymore. The primary condition is now number of active copies, and after that it was round robin. Now with this new version the secondary round robin is replaced with a sort by free space.

The blocking of drives will disturb the round robin because it's all asynchronous and there is also a re-try on failure. So the algorithm cannot provide a perfect round robin anymore because of all the conditions there are now.

**Comment by madMAx43v3r** [comment]
[cuda_plot_better_round_robin.zip](https://github.com/madMAx43v3r/chia-gigahorse/files/10816202/cuda_plot_better_round_robin.zip)

Ok try this, next copy will now be the next drive after the last one, if everything else is equal, ie. no active copies and all have the exact same free space.

**Comment by Jacek-ghub** [comment]
Thank you.  Starting it right now.

**Comment by Jacek-ghub** [comment]
Something is not right this time.  The first 2 plots went as they should, but after that all goes to d2 (d1 is blocked).

plotter version - b61645a
```
Chia k32 next-gen CUDA plotter - b61645a
Plot Format: mmx-v2.4
Network Port: 11337 [MMX] (unique)
No. GPUs: 1
No. Streams: 4
Final Destination: /mnt/nvme/mmx/tmp1/d1/
Final Destination: /mnt/nvme/mmx/tmp1/d2/
Final Destination: /mnt/nvme/mmx/tmp1/d3/
Final Destination: /mnt/nvme/mmx/tmp1/d4/
Final Destination: /mnt/nvme/mmx/tmp1/d5/
Final Destination: /mnt/nvme/mmx/tmp1/d6/

  Started copy to /mnt/nvme/mmx/tmp1/d2/plot-mmx-k32-c7-2023-02-23-09-35-f13445785ea1eaae6a537c0ab205d3c3fb4d60fc8cfe56bf49fb2033bdc0a6cd.plot
  Renamed final plot to /mnt/nvme/mmx/tmp1/d2/plot-mmx-k32-c7-2023-02-23-09-35-f13445785ea1eaae6a537c0ab205d3c3fb4d60fc8cfe56bf49fb2033bdc0a6cd.plot
Started copy to /mnt/nvme/mmx/tmp1/d3/plot-mmx-k32-c7-2023-02-23-09-39-6634fa18c00e9c671ce7dc34ca8b3c1d3aa10dc222d2b2bb9ed79eab0cd49a42.plot
Renamed final plot to /mnt/nvme/mmx/tmp1/d3/plot-mmx-k32-c7-2023-02-23-09-39-6634fa18c00e9c671ce7dc34ca8b3c1d3aa10dc222d2b2bb9ed79eab0cd49a42.plot
  Started copy to /mnt/nvme/mmx/tmp1/d2/plot-mmx-k32-c7-2023-02-23-09-42-8a0bed46e7414bcf4d08e3c18711e867290ae32629a7781cdaaf40a5964d2686.plot
  Renamed final plot to /mnt/nvme/mmx/tmp1/d2/plot-mmx-k32-c7-2023-02-23-09-42-8a0bed46e7414bcf4d08e3c18711e867290ae32629a7781cdaaf40a5964d2686.plot
  Started copy to /mnt/nvme/mmx/tmp1/d2/plot-mmx-k32-c7-2023-02-23-09-44-3e99cb94db557bac8f5d3c088d9c3a5ce26278a87002ac56e509b895dffaff0f.plot
  Renamed final plot to /mnt/nvme/mmx/tmp1/d2/plot-mmx-k32-c7-2023-02-23-09-44-3e99cb94db557bac8f5d3c088d9c3a5ce26278a87002ac56e509b895dffaff0f.plot
  Started copy to /mnt/nvme/mmx/tmp1/d2/plot-mmx-k32-c7-2023-02-23-09-47-a896fa7f32628b036ac45bd223a701f46eb93057fa43183ea1db849c0b326d0d.plot
  Renamed final plot to /mnt/nvme/mmx/tmp1/d2/plot-mmx-k32-c7-2023-02-23-09-47-a896fa7f32628b036ac45bd223a701f46eb93057fa43183ea1db849c0b326d0d.plot
  Started copy to /mnt/nvme/mmx/tmp1/d2/plot-mmx-k32-c7-2023-02-23-09-49-a038d9fa681203385277b152aae62f9987579e4eb96a33a5049e6a86ec2c354d.plot
  Renamed final plot to /mnt/nvme/mmx/tmp1/d2/plot-mmx-k32-c7-2023-02-23-09-49-a038d9fa681203385277b152aae62f9987579e4eb96a33a5049e6a86ec2c354d.plot
  Started copy to /mnt/nvme/mmx/tmp1/d2/plot-mmx-k32-c7-2023-02-23-09-52-b62d6716a362f83383eab1fdf78f4ce0cec7efeb9f7970a015102118fed13545.plot
  Renamed final plot to /mnt/nvme/mmx/tmp1/d2/plot-mmx-k32-c7-2023-02-23-09-52-b62d6716a362f83383eab1fdf78f4ce0cec7efeb9f7970a015102118fed13545.plot

```

**Comment by madMAx43v3r** [comment]
hmm, hows that even possible? are you plotting slow enough that only one HDD is busy at a time?

**Comment by Jacek-ghub** [comment]
There are 6 drives connected.  4x are SATA, 2x are USB.  When the backup is building up (before this release), all but d2 were finishing well before the next plot was scheduled for that drive.  Plotting speed is ~150 seconds or so.  There are no "waits" in the plotter, it is running at a full speed.

That last run was really strange, all the previous ones were basically (n+1) for the next drive after the plotted one.

**Comment by madMAx43v3r** [comment]
I should have tested it myself first, try this fix, works for me:
[cuda_plot_fixed_round_robin.zip](https://github.com/madMAx43v3r/chia-gigahorse/files/10816959/cuda_plot_fixed_round_robin.zip)

**Comment by Jacek-ghub** [comment]
Perfect.  This version works like a charm!!

Thank you, Max!  I really appreciate this change.

I will close it as a new feature now.

**Comment by madMAx43v3r** [comment]
Good to know, thanks for testing.
