### ISSUE TITLE
C9 PLots VRam requirements 

### ISSUE THREAD

**Issue by Kruger1981** [madMAx43v3r/chia-gigahorse#215]
At the moment I have a mix of c7 and c8 plots being farmed on a RTX A2000 6GB.
I see that fo c9 plots vRam requirements are just over 6GB vRam.
I have another RTX A2000 that its not being used, if I put both A2000 6gb on the same machine will technically have 12gb vRam. Would this work for c9 plot farming or would each card need to have the minimum amount of vRam necessary?

**Comment by zhurakovsky01** [comment]
Каждая карта должна иметь минимально необходимое кол-во памяти. Память ВК не суммируется.
