### ISSUE TITLE
Failed to initialize OpenCL device [0]: failed to compile OpenCL kernels

### ISSUE THREAD

**Issue by AtomicInternet2** [madMAx43v3r/chia-gigahorse#221]
Should probably include in notes for 1.8.2.giga21 Gigahorse 2.0:

- New **chia_recompute_server** is not currently functional with OpenCL 

I'm able to run it just fine with 1.8.2.giga14 on my Ryzen 7 5700G.
Latest version reports on Windows 11:
```
[chiapos] Using 16 / 16 CPU threads
[chiapos] Using 0 / 0 CUDA devices
[chiapos] Failed to initialize OpenCL device [0]: failed to compile OpenCL kernels
[chiapos] Using 0 / 1 OpenCL devices (AMD Accelerated Parallel Processing)
Using 16 / 16 CPU threads
ReComputeServer listening on 0.0.0.0 port 11989
[1697918363949] Request from 192.168.0.181 for K32 C7 took 2682.02 ms (used_gpu = 0, is_fail = 0)
[1697918364165] Request from 192.168.0.181 for K32 C7 took 2532.38 ms (used_gpu = 0, is_fail = 0)
[1697918364718] Request from 192.168.0.181 for K32 C7 took 2717.55 ms (used_gpu = 0, is_fail = 0)
```

**Comment by AtomicInternet2** [comment]
CLInfo from machine
`Number of platforms:                             1
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.1 AMD-APP (3570.0)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices


  Platform Name:                                 AMD Accelerated Parallel Processing
Number of devices:                               1
  Device Type:                                   CL_DEVICE_TYPE_GPU
  Vendor ID:                                     1002h
  Board name:                                    AMD Radeon(TM) Graphics
  Device Topology:                               PCI[ B#48, D#0, F#0 ]
  Max compute units:                             8
  Max work items dimensions:                     3
    Max work items[0]:                           1024
    Max work items[1]:                           1024
    Max work items[2]:                           1024
  Max work group size:                           256`

**Comment by madMAx43v3r** [comment]
Yeah, it compiles with Nvidia driver, but not with AMD / Intel for some reason...

**Comment by madMAx43v3r** [comment]
[chiapos_fix_for_opencl.zip](https://github.com/madMAx43v3r/chia-gigahorse/files/13063114/chiapos_fix_for_opencl.zip)

Try this fix for now, just replace the `chiapos.so` in your `chia-gigahorse-farmer`.

**Comment by madMAx43v3r** [comment]
Should be fixed now: https://github.com/madMAx43v3r/chia-gigahorse/releases/tag/v1.8.2.giga22

**Comment by AtomicInternet2** [comment]
Thanks for the fast response!  Works perfect!
