### ISSUE TITLE
When will this be updated to Chia 2.1.3?

### ISSUE THREAD

**Issue by eliliam** [madMAx43v3r/chia-gigahorse#252]
There were several fixes included in both Chia version 2.1.2 and 2.1.3 that help with the stale partial issue that I(and likely many others) have been noticing both in the Gigahorse farmer and the original Chia farmer with version 2.1.1 that has since been fixed. This is causing lost revenue for farmers and likely for MadMax himself due to less blocks won. When are you planning on updating the repo to match the latest Chia client version?

**Comment by ichimars** [comment]
Many stales began to show in pool stistics after chia's update starting from 18-12-23. Node is fully synced and all is ok. Changing pool did not solve this problem.  Maybe it is because of the update.

**Comment by LimakKAAM** [comment]
My farm stopped. No sending partial and very higm missing signature point.

**Comment by madMAx43v3r** [comment]
2.1.3 available now
