### ISSUE TITLE
Harvester - Missed deadline for height ... (using remote recompute_server)

### ISSUE THREAD

**Issue by Jacek-ghub** [madMAx43v3r/chia-gigahorse#255]
Not sure if I understand that warning correctly.  From what I understand, 
1. harvester is passing a batch of challenges to remote-recompute
2. challenges are processed serially all challenges in the batch (based on the recompute output)
3. recompute returns all results back to the harvester
4. harvester checks the deadline, and if the block submission deadline is missed, it issues the above warning, what leads to a loss of the batch

If such case, the whole batch of challenges is being lost, potentially to just a couple of extra challenges.  In case this happens, all those the processing time for those few extra challenges is wasted (as is the whole batch of challenges), and also is further interfering with batches that are waiting (basically compounding congestion).  

Would it be possible for the harvester to also pass a deadline (whatever harvester thinks about it) to recompute, so the recompute would stop processing the batch once it reached that deadline and return back only those challenges that were successfully processed?

I know this is rather a marginal case (if I understand it right at all), but maybe it could be done in some spare time.

**Comment by madMAx43v3r** [comment]
"Missed deadline for height" is a MMX warning, and it means that the compute / lookups for that height are not even attempted, so nothing is wasted.

**Comment by Jacek-ghub** [comment]
Great!  Thank you.

Yes, I was trying to use k2200 to handle 1 JBOD (12x 18TB C7/C8 ~50% each) for MMX using the latest GH recompute-server.  However, it cannot handle it on my setup.  Not a big deal, as it was just for testing, as I have 3060 ti as well.

By the way, would it be possible to add "height" to recompute-server logs for each challenge processed?  It will be easier to trace what it is doing.

I will close this ticket then.

**Comment by Jacek-ghub** [comment]
I misunderstood how it is being handled, so closing as there is nothing to fix.

**Comment by Jacek-ghub** [comment]
Nothing to fix.

**Comment by Jacek-ghub** [comment]
> By the way, would it be possible to add "height" to recompute-server logs for each challenge processed? It will be easier to trace what it is doing.

If you decide to do that, maybe you could also add harvester name to those lines.
