### ISSUE TITLE
GPU Plotter Stalls

### ISSUE THREAD

**Issue by Acer854** [madMAx43v3r/chia-gigahorse#26]
System: Ryzen 5800X ; 64 GB ; 2 TB PCIe3 NVME ("p:\" below) ; GPU1: RX6800 (not used) ; GPU2: Tesla P4. ; OS: Win11.

Command: ......\cuda_plot_k32.exe -C 8 -n 1 -t p:\ -3 p:\ -d p:\ -c xxxxxxxxxxx -f xxxxxxxx -M 32

Problem: Plotter stalls on Phase 1 Table 3 or 4. GPU sometimes remains pegs at 100% or falls to 0%. NVME disk activity falls to zero. RAM remains pegged at ≈63 of 64gb.  No error messages displayed in plotter, plotter just stops. When restarting plotter, sometimes requires system restart to avoid error message of zero devices available. 

Any ideas?

EDIT: The PCIe slot that the Tesla P4 is in runs at x4, not x16, if that makes a difference.

**Comment by Acer854** [comment]
Add: RAM remains utilized at ≈ 63gb of 64gb.

**Comment by madMAx43v3r** [comment]
probably not enough free RAM

**Comment by Acer854** [comment]
Turned out to be a hardware issue. Closing.
