### ISSUE TITLE
chia_recompute_proxy hangs compute if a single host is unreachable

### ISSUE THREAD

**Issue by zivester** [madMAx43v3r/chia-gigahorse#261]
If you give `chia_recompute_proxy` IPs that are under maintenance (e.g. they cannot connect), they will hang and stop processing of all computes.  If a node is not responding it should fail and defer to other hosts.

```bash
$ ./chia_recompute_proxy -n 192.168.41.102 -n 192.168.0.101 -n 192.168.40.99
Node: 192.168.41.102 (port 11989)   // Host OFF
Node: 192.168.0.101 (port 11989)  // Host ON
Node: 192.168.40.99 (port 11989)   // Host OFF
ReComputeProxy listening on 0.0.0.0 port 11989
Node 192.168.41.102 failed with: connect() failed with: Connection timed out (110)
[1705432863720] Request from 127.0.0.1 forwarded to node 192.168.0.101
Node 192.168.41.102 failed with: connect() failed with: Network is unreachable (101)
Node 192.168.40.99 failed with: connect() failed with: Connection timed out (110)
[1705432994455] Request from 127.0.0.1 forwarded to node 192.168.0.101
Node 192.168.41.102 failed with: connect() failed with: Network is unreachable (101)
```

**Comment by madMAx43v3r** [comment]
>  If a node is not responding it should fail and defer to other hosts.

It's actually doing that, but the `connect()` calls blocking until the error is the problem. This is a known issue.

**Comment by madMAx43v3r** [comment]
You can try the new version [in master](https://github.com/madMAx43v3r/chia-gigahorse/tree/master/chiapos/linux/x86_64). Should be fixed.

**Comment by zivester** [comment]
It no longer indefinitely hangs, but it basically adds enough latency into compute where it seems unusable.  After replacing hosts from 1 good host to 1 good and 3 bad, my latency graphs look like this:

![image](https://github.com/madMAx43v3r/chia-gigahorse/assets/438348/f5be6cbf-f69d-4ff8-a6ef-202d8b71becb)

Now 2 hosts that are up (w/ an IP) vomit in the logs as we would expect.

![image](https://github.com/madMAx43v3r/chia-gigahorse/assets/438348/aa261ba3-a5c3-46ae-a8f3-b95c1f657d7e)

The last host is not on, it doesn't error in the logs (or I can't tell cause the others fail much faster).

That said, the resolution to the only good host basically happens at too slow a cadence and I just see a slow trickle of requests it can handle in ~500ms.  My usual stream of proofs from my pool usually happens in ~6s and they peak at like 1200ms.

![image](https://github.com/madMAx43v3r/chia-gigahorse/assets/438348/c5181223-5a7b-4293-8d36-0b6b30e79e40)

Definitely progress, but in my head I would hope bad hosts would add neglible overhead for proof resolution.  But currently that's still not the case.

![image](https://github.com/madMAx43v3r/chia-gigahorse/assets/438348/7d7db1e4-acbb-4447-b9fb-f3bae1d0ee53)

**Comment by madMAx43v3r** [comment]
You need to use the new `chia_recompute_server` to get accurate timings with the new proxy. Because the new proxy opens the connection before sending the actual request, and the old server starts counting the time when the connection is established.

And it seems the harvester latency goes up because you just don't have enough compute when disabling too many hosts?

**Comment by madMAx43v3r** [comment]
The log vomit is an issue yes, will fix.

**Comment by madMAx43v3r** [comment]
There might have been an issue when adding lots of IPs which refuse to connect quickly. Let's try latest version in master.

**Comment by madMAx43v3r** [comment]
> Looks like you went back to the original backoff of 5-10s before trying a host again?

10 sec yes

> and the offline host fails after a second or 2.

Try using an external IP like 1.2.3.4 that doesn't respond, ie. timeout, in this case it takes 1-2 min to fail.
