### ISSUE TITLE
Suppressing lookups for all except the current challenges

### ISSUE THREAD

**Issue by Jacek-ghub** [madMAx43v3r/chia-gigahorse#267]
If the harvester is loaded close to GPU capacity, there are problems with lookups when harvester starts, as it is trying to do lookups for the past 5 challenges.  This basically chokes the GPU for quite a bit.  It also causes a bunch of stales / long lookups on the pool side and that messes up charts (e.g., FoxyPool).

Would it be possible to add to config.yaml harvester entry (e.g., harvester: / past_lookups: False) to suppress this behavior?

**Comment by madMAx43v3r** [comment]
This would have to be fixed in the full node, and I think it's not easy...
