### ISSUE TITLE
Ryzen 7 8700G iGPU:  recompute failed to produce a candidate

### ISSUE THREAD

**Issue by AtomicInternet2** [madMAx43v3r/chia-gigahorse#268]
First off I VERY MUCH APPRECIATE your inclusion of OpenCL for recompute farming.  
It lets me leverage the iGPUs in my Ryzen 7 5700G machines to the fullest.

I'm currently still farming with my Ryzen 7 5700G machines, but upgraded my primary workstation to a Ryzen 7 8700G and for giggles tried to use the recompute on it.  Unfortunately even after installing the latest VC++ redistributable I get the "exception fetching qualities" from the iGPU.

I'm confident this is very low on your list of priorities, but if you just have to recompile with latest AMD drivers I'll happily test any binary you have the time to throw at me.  

I've attached the recompute fail logs and my clinfo output if that's helpful at all.

[clinfo.txt](https://github.com/madMAx43v3r/chia-gigahorse/files/14214168/clinfo.txt)

[recompute_fail.txt](https://github.com/madMAx43v3r/chia-gigahorse/files/14214173/recompute_fail.txt)

**Comment by AtomicInternet2** [comment]
[proofofspace.txt](https://github.com/madMAx43v3r/chia-gigahorse/files/14214954/proofofspace.txt)

**Comment by madMAx43v3r** [comment]
Looks like a driver bug as is often the case with AMD...

**Comment by mwpastore** [comment]
Ryzen 5000G is Vega
Ryzen 7000 (non-F) is RDNA2
Ryzen 8000G is RDNA3

**Comment by AtomicInternet2** [comment]
This issue has been resolved in the latest release (2.4.0.giga36) with Adrenalin driver 24.5.1.  
I'm able to recompute successsfully on my 8700G iGPU now. 
Thank you!

`C:\Users\atomi\Downloads>chia_recompute_server.exe`
`[chiapos] Using 16 / 16 CPU threads`
`[chiapos] Using 0 / 0 CUDA devices`
`[chiapos] Using 1 / 1 OpenCL devices (AMD Accelerated Parallel Processing)`
`Using 16 / 16 CPU threads`
`Using gfx1103 (AMD Accelerated Parallel Processing)`
`ReComputeServer listening on 0.0.0.0 port 11989`
`[1719231923403] Request from 192.168.0.181 for K32 C7 took 207.691 ms (used_gpu = 1, is_fail = 0)`
`[1719231923525] Request from 192.168.0.181 for K32 C7 took 171.236 ms (used_gpu = 1, is_fail = 0)`
`[1719231923644] Request from 192.168.0.181 for K32 C7 took 217.4 ms (used_gpu = 1, is_fail = 0)`
