### ISSUE TITLE
Running ProofOfSpace under win10, a strange prompt appears:

### ISSUE THREAD

**Issue by xieyusi9** [madMAx43v3r/chia-gigahorse#27]
PS D:\> Measure-Command {./ProofOfSpace lookup -r 8 -f plot-k32-c8-2023-02-27-13-05-24c464f26aa358db1bf2ddb1dd182e3abfe130c45512e6561ec1407e793d22e8.plot|Out-Default}
operation: lookup
[chiapos] Using 16 / 16 CPU threads
[chiapos] Using 1 / 1 CUDA devices
[chiapos] Using 2 / 2 OpenCL devices (AMD Accelerated Parallel Processing)
Threw: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_INVALID_CONTEXT
Threw: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_INVALID_CONTEXT
Threw: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_INVALID_CONTEXT
Threw: bad allocation
Threw: bad allocation
Threw: bad allocation
Threw: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_INVALID_CONTEXT
Threw: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_INVALID_CONTEXT
Threw: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_INVALID_CONTEXT
Threw: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_INVALID_CONTEXT
Threw: bad allocation
Threw: bad allocation
Threw: bad allocation
Threw: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_INVALID_CONTEXT
Threw: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_INVALID_CONTEXT
Threw: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_INVALID_CONTEXT
Threw: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_INVALID_CONTEXT
Threw: bad allocation
Threw: bad allocation
Threw: bad allocation
Threw: bad allocation
Threw: bad allocation
Threw: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_INVALID_CONTEXT
Threw: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_INVALID_CONTEXT
Threw: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_INVALID_CONTEXT
Threw: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_INVALID_CONTEXT
Threw: bad allocation
Threw: bad allocation
Threw: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_INVALID_CONTEXT
Threw: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_INVALID_CONTEXT
Threw: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_INVALID_CONTEXT
Threw: bad allocation
Threw: bad allocation
Threw: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_INVALID_CONTEXT
Threw: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_INVALID_CONTEXT
Threw: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_INVALID_CONTEXT
Threw: bad allocation
Threw: bad allocation
Threw: bad allocation

......
......

**Comment by xieyusi9** [comment]
If you use the previous version of ProofOfSpace will appear:


PS D:\> Measure-Command {d:\ProofOfSpace.exe lookup -r 8 -f d:\plot-k32-c8-2023-02-27-13-05-24c464f26aa358db1bf2ddb1dd182e3abfe130c45512e6561ec1407e793d22e8.plot|Out-Default}
operation: lookup
[chiapos] Using 16 / 16 CPU threads
[chiapos] Using 1 / 1 CUDA devices
i: 375
challenge: 0x0936e07f5af4a22c02343a8bdd8e83bdc22fba0626058d03985ee9bcfb752eb2
quality: b1000111011110101001010110000111111111001110011111011000011010101111000111000110000000100100011110010111100100000010110101010001100101011101011000000110000011111101101110010010000110011000001110100111100011011001000101110111110101100010101001000011100100001
i: 750
challenge: 0x1ed4ccb6166f0d83b92177b9a973334793dc77edc1dc46ed3f72193346f48f2c
quality: b0010000011010110101101001001110111000001001101110110100001110101100000100110010000100001000100011100110100001000010010001111101100010110110100110100010101010010100101001101111001001100100110100010011111000110011010000110000101001001000011100110110101110010
Threw: bad allocation
Threw: bad allocation
Threw: bad allocation
Threw: bad allocation
i: 875
challenge: 0x71db6045036361d5be8fb7cb8689734e812be26175397f477f7c74746206c8cc
quality: b1001100000001011110001100111010000010000110100110100010110111010000111000001101010110100110101001101000110010000111001001110000001010100000000111110100111110100000110100111001010000011111100000111101000101011110110000101101001101011000101100100010110110011
Threw: bad allocation
Threw: bad allocation
Threw: bad allocation
Threw: bad allocation
i: 377
challenge: 0xe58c886221aa1e78d3466eea9f28a7bd1940ccd606cafd3ef37f55e8440e593b
quality: b1001111000100110101011100100000010100110001111100000101100000011100110101011101100110101101110100000100010101110110010101001111100000101010001110010000001101001100001111100100100100001111101000000110101001111100001000100111010010111000111110110001100011001
i: 250
challenge: 0x6416f0c2b69bd6714a3a50fb2196e5088c86673a9d1e8e6f765d399f946d9f78
quality: b0101111010000111110101000100100110000001010100000100100011111101010000100111011001100011011100010100000011011011011111011111110000110111011110100101011010111011100010101000110010001000000110100111000110100000000000100101100101100011100000011111000001100111
i: 250
challenge: 0x6416f0c2b69bd6714a3a50fb2196e5088c86673a9d1e8e6f765d399f946d9f78
quality: b1111001111010100001110001101011100010001011101111110011100001111000100001011010010001010101100111001111000000111100010011000101000100111010000000101100001110110110101100000111100110100010001010111010101110010000010011000111010110001011000111000000011011111
Threw: bad allocation
Threw: bad allocation
Threw: bad allocation
Threw: bad allocation
i: 625
challenge: 0x02cf21712b32ba658b731f567382c2e935de00a88bc36dc019d6c09777d8363f
quality: b0100010000010101011111011110010001111001001010100110011010111010101010011110101100001010100000000001011011100111110111101010100100000011010010010101100101110001100010001100111111000011010110100001000010111001101100010110110111000101111101100101010000111001
i: 625
challenge: 0x02cf21712b32ba658b731f567382c2e935de00a88bc36dc019d6c09777d8363f
quality: b1111111011100000001011000101001001001101111101101110001000000110000110100110000000010011011110010110110011111101010110111000010001110001111011010000100010011001100000010111010101100010101000111010100001001011101001100001001010000011000111111111110110001101
i: 1
challenge: 0xe831db50592e771271fd2b18672407d7882d6a64e5acfd8d48d09692e86b5551
quality: b0110110011100100111111001101101101111110110110001011110110010000010100001001101110000111111111100101011110110111011111101001101110101000010100101011011010001101000111010101010011000010010001010100000111101100111010001101110011000001001001101110101111011110
i: 1
challenge: 0xe831db50592e771271fd2b18672407d7882d6a64e5acfd8d48d09692e86b5551
quality: b0010010110000010011010011010010100110110100111100111000001111001101110001100101000001110001010010011000110101001110100110001101011001110101001101011110000110101001010111010101111001011111000000001000100101100010110111010100110011100101101100101100110110110
i: 882
challenge: 0xb07bdc0f3d2b5f224eee20269dbdd314c55809de7c6c06f5462e29ae0be7e1d3
quality: b1101010001110000010000110010110111011001100110110110001011010010111100100000001010111101000100011000101110011010111011011100000001111101010010000101111110001110000110111011111111101101011010111000010010011111101011010001010000110011101011001101000101011011
Threw: bad allocation
Threw: bad allocation
Threw: bad allocation
Threw: bad allocation
Threw: bad allocation
i: 125
challenge: 0xffd38cdfdb407977d5c418a939df6df0ed69daa555666b9ec7522ee6de12a96c
quality: b0001110101110101011111111101000100100111010000001010010100011100100100111101000001111101010011110110101100101000110011011011011110011101001100100101010011110000110100001010010100010111010100111100011100010010100011110011111101011010011101110110011011001010
i: 626
challenge: 0xa0ebcfe11a008917f3b930218e2dbe122db88e51b68e29195df246394df676bc
quality: b1111001100111011011111100000111000111010100001111010111001110111011000110110001101111011110111010001110110000010111111100011011110001000100011011001000000101100100110101100111110101100110111011110110101101110110010110100001101001000011011001100100110111110
Threw: bad allocation
Threw: bad allocation
Threw: bad allocation
Threw: bad allocation
i: 378
challenge: 0xae03226f1bfc04f76d0dc40c1ac747d4e8cb2d7957af54a22b0991b6d4eafba2
quality: b0011010010011011001100010011100010010111010001001100001100010000000110010011111111011010100100011001001011100000110011101011001001010100011111000010101001100110101011000000000001011001011101001100010000110000011111010010110101110000110000011100000011101100
i: 378
challenge: 0xae03226f1bfc04f76d0dc40c1ac747d4e8cb2d7957af54a22b0991b6d4eafba2
quality: b1001110011001111100111100010110000100011011100010010111110000100010001101101010100111011001110100001010101011010010101100110100011000001101010011100011101001000111111001111010001000001001110111110011110110001010111000110100000010100000011010110110111110000
i: 751
challenge: 0x9f1a99f16f577a9fe3481b7a6b1b1cfc8dfc5bb8bcc815a92a3ee217178eed9d
quality: b1100111111011000110111000100010001111011101101110110111100011101001011100111000001111001110100110100111001100111000110110110100001110111010010011010011010101001101000000101110100101101010111011001000101011000011010000001011001100010010001000101110010001110
i: 751
challenge: 0x9f1a99f16f577a9fe3481b7a6b1b1cfc8dfc5bb8bcc815a92a3ee217178eed9d
quality: b0010001000101110110001110010100110011011000110000010100101110100010101101111110001110001001010111001101011110000000010110100010111110000011100101110000001110110001101011111010001100001100111110000110111111111001110111101101001110000000011010010101101101100
i: 751
challenge: 0x9f1a99f16f577a9fe3481b7a6b1b1cfc8dfc5bb8bcc815a92a3ee217178eed9d
quality: b0011010101100100111000001011011011011101111110010000001011101111110110010111010101001101100001100010100110011010111110011100110101000111011001100110010001101001010110000000011110110000001010001010101110001100101011010011000000010110111110111010010010001111
Threw: bad allocation
Threw: bad allocation
i: 627
challenge: 0x4ff19d825f3abc65547f0c9a81b77d6fceba5b276cc4abfc5049aacb434d7c2e
quality: b0101111000001111110111011101011110010100110111101100101111010110111111110011100111100010110011000000100101001100011100001101011010000110001011000101010011000011000000011001101011010100001111111011101011110010001101000001110010001011000000010100011111010001
i: 2
challenge: 0x918ff4c1b3bd1348e172b4963a0c22008bcaefd84efa3cbb78aa0228897af0c9
quality: b1000000010111010101100101011000000001101111010101000010110110111011100011011101010111101100001000110111000111011000010101100100101100000011101111111110000101001111010111101010100100010011001011101110110010111111001001011101010110010011011000010101101111000
i: 2
challenge: 0x918ff4c1b3bd1348e172b4963a0c22008bcaefd84efa3cbb78aa0228897af0c9
quality: b0101111110000001010111000100100001101001000011110101001110110100111001011011000101011101010110001000100001110101001111101001101011011000011000011100000100100010011000100011001110001100101011110010100111101111110011000000001010101000101100010011010101111001
Threw: bad allocation
Threw: bad allocation
Threw: bad allocation
Threw: bad allocation

......
......

**Comment by xieyusi9** [comment]
The hardware I am using is: Lenovo Legion R9000P
The latest version of the graphics card driver is installed

**Comment by madMAx43v3r** [comment]
Looks like it found some OpenCL GPUs, what are those?

Try to limit to one OpenCL device, maybe there is an issue with multiple:  `export CHIAPOS_MAX_OPENCL_DEVICES=1`

**Comment by xieyusi9** [comment]
This command is invalid under win10

**Comment by madMAx43v3r** [comment]
Oh sorry yes, anyways I found the issue and fixing it now...

**Comment by xieyusi9** [comment]
This laptop CPU integrates a nuclear display Radeon Vega8

**Comment by madMAx43v3r** [comment]
can you show screenshot of task manager performance tab?

looks like there is two AMD GPUs...

**Comment by xieyusi9** [comment]
![image](https://user-images.githubusercontent.com/110649504/221559509-2b3b2b81-bb7d-4f24-8934-5400fb486861.png)

Sorry, this is the Chinese version of the operating system, I don't know if you can understand it

**Comment by madMAx43v3r** [comment]
Try latest `ProofOfSpace`, should be fixed.

Still strange why it detected two GPUs via AMD OpenCL platform...

**Comment by madMAx43v3r** [comment]
You can also try https://github.com/madMAx43v3r/chia-gigahorse/releases/tag/v1.6.2.giga7

Has the fix for the farmer.

**Comment by xieyusi9** [comment]
![image](https://user-images.githubusercontent.com/110649504/221564406-68a80397-6d30-49f0-a72d-2316ba6c14b1.png)
![image](https://user-images.githubusercontent.com/110649504/221564535-8b007412-89b0-4bf4-bcb9-e2478c7698f1.png)

Environment variable cannot disable OpenCL

**Comment by madMAx43v3r** [comment]
Did you open a new terminal?

**Comment by xieyusi9** [comment]
No new terminal

**Comment by madMAx43v3r** [comment]
Setting `CHIAPOS_MAX_OPENCL_DEVICES` to `0` should work

**Comment by xieyusi9** [comment]
It's really strange. Restart the system and it will be normal. Thank you!
