### ISSUE TITLE
Upgrade to Chia 2.2.1

### ISSUE THREAD

**Issue by eliliam** [madMAx43v3r/chia-gigahorse#272]
Chia version 2.2.1 just came out, when can we expect a version bump here to go along with it?

**Comment by madMAx43v3r** [comment]
Later, it's a lot of work.

**Comment by eliliam** [comment]
Closed with [v2.2.1.giga33](https://github.com/madMAx43v3r/chia-gigahorse/releases/tag/v2.2.1.giga33)
