### ISSUE TITLE
How to set environment variables under win10?

### ISSUE THREAD

**Issue by xieyusi9** [madMAx43v3r/chia-gigahorse#28]
Why is it invalid to set environment variables under win10? How to turn off the GPU in win10?

set CHIAPOS_MAX_CUDA_DEVICES=0
setx CHIAPOS_MAX_CUDA_DEVICES 0

Tried both, nothing changed

**Comment by madMAx43v3r** [comment]
https://www.google.com/search?channel=fs&client=ubuntu&q=windows+set+environment+variable
