### ISSUE TITLE
sending to plot_sink EOF error

### ISSUE THREAD

**Issue by romka1977** [madMAx43v3r/chia-gigahorse#287]
plotting to plot_sink results in error:

```
./cuda_plot_k32_v3 -n 1 -f b46788<...>fbd1 -c xch1<...>yv7k -t /tmp3/chia/tmp/  -d @192.168.1.97 -S 2 -C 33

Started copy to @192.168.1.97:plot-<....>33f3.plot
Copy to @192.168.1.97:plot-<...>33f3.plot failed with: recv() failed with: EOF
```

**Comment by madMAx43v3r** [comment]
Did you update plot sink to latest version? Also what is the terminal output on plot sink?

**Comment by romka1977** [comment]
yes, plotsink was downloaded yesterday (along with the farmer and plotter).
recompute works fine on the same remote (192.168.1.97)
telnet from plotter machine to 192.168.1.97 1337 is working (have a prompt)
plotsink terminal is:

```
Final Directory: /mnt/d/chia/plots_comp/ (77 GiB free)
Final Directory: /mnt/e/chia/plots_comp/ (109 GiB free)
Final Directory: /mnt/f/chia/plots_comp/ (106 GiB free)
Final Directory: /mnt/g/chia/plots_comp/ (122 GiB free)
Final Directory: /mnt/h/chia/plots_comp/ (122 GiB free)
Listening on 0.0.0.0:1337

```
silent after that

**Comment by madMAx43v3r** [comment]
is that while plotting, ie. the plotter is trying to send plots? Did you use the correct IP in the plotter?

**Comment by romka1977** [comment]
yes, while plotting. (command line is in the original post)
IP is correct. I tried with incorrect IP - the error is different in this case (didnt capture it but it didnt have EOF)
Essentially plotter is trying to send it periodically to that remote sync with the same error.

(currently im plotting with multiple -d's as a workaround. not using sink)

**Comment by madMAx43v3r** [comment]
Can you try the old version here: https://github.com/madMAx43v3r/chia-gigahorse/tree/8fd24a08c89245b8f4794079ee15fb63f1d2cbbb/plot-sink

**Comment by madMAx43v3r** [comment]
You're not using WSL or anything?

**Comment by romka1977** [comment]
i can try

i use WSL, however recompute works fine in the same VM

**Comment by madMAx43v3r** [comment]
maybe try a different port for plot sink then

**Comment by romka1977** [comment]
ok, how do i specify the arbitrary sink port in plotter cli? @IP:PORT ?

**Comment by romka1977** [comment]
seems to be an issue with specifying the port:

```
./cuda_plot_k32_v3 -n 1 -f b467<...>1a11fbd1 -c xch1<...>gjyv7k -t /tmp3/chia/tmp/ -d @192.168.1.97:11990 -S 3 -C 32 & 

<...>

Started copy to @192.168.1.97:11990:plot-<...>1640.plot
Copy to @192.168.1.97:11990:plot-<...>1640.plot failed with: could not resolve: '192.168.1.97:11990'
Started copy to @192.168.1.97:11990:plot-<...>1640.plot
Copy to @192.168.1.97:11990:plot-<...>1640.plot failed with: could not resolve: '192.168.1.97:11990'
```

**Comment by madMAx43v3r** [comment]
Ah sorry, yes need to use `-z <port>` instead.

**Comment by romka1977** [comment]
tried 11990 - doesnt work. I resorted to windows sink on the host machine and it works on default port.
Anyways, thanks for your time, im done now

**Comment by madMAx43v3r** [comment]
yeah probably some WSL issue
