### ISSUE TITLE
Plots Failed to open As problem with start_farmer.sh or ubuntu linux ?

### ISSUE THREAD

**Issue by DMJ777** [madMAx43v3r/chia-gigahorse#299]
![PR1](https://github.com/madMAx43v3r/chia-gigahorse/assets/166164910/1d09c47c-dc13-4111-b41a-43d51afa6935)
![PR2](https://github.com/madMAx43v3r/chia-gigahorse/assets/166164910/0064b7f6-e7bc-4f9a-8f01-831d75ec5339)

After few days to work with Ubuntu ,set up everything , and Gigahorse plotting fine 
Install chia , version of chia is same as gigahorse (tried as well different versions)

I know a problem can be as need run start_farmer.sh and plots come valid at next Chia Gui start , but not in my case. 
As you see daemon start normal as should be ,but when run chia there is no warning version come (may be because same but when been different as well not appear) ,  as plots still invalid.

I loose any patience and not find any solution online for a day.
Please help me to resolve this issue? Regards

**Comment by madMAx43v3r** [comment]
Can you try the GH GUI here: https://github.com/madMAx43v3r/chia-gigahorse/releases/tag/v2.2.1.giga35

Download `chia-blockchain_2.2.1.giga35_amd64.deb` and install via `sudo dpkg -i chia-blockchain_2.2.1.giga35_amd64.deb`.

**Comment by DMJ777** [comment]
Your instruction is best  , after i install gigahorse its start working ,
The problem been , that i not install package but extract this only .
You are good man , God bless you
![gr5](https://github.com/madMAx43v3r/chia-gigahorse/assets/166164910/92029a3c-1942-4779-9b9f-e4394f1a5905)
