### ISSUE TITLE
Failed to allocate MEM_TYPE_DEVICE : CUDA error 2 : out of memory

### ISSUE THREAD

**Issue by DMJ777** [madMAx43v3r/chia-gigahorse#303]
![7b6785a8-77b5-4fc3-af9b-b7e2bd36e2c6](https://github.com/madMAx43v3r/chia-gigahorse/assets/166164910/cff01ba2-4e86-4ac7-89bf-1e35ac0ad270)
![4905f169-1764-4b3a-bdf7-2cb044bea7a2](https://github.com/madMAx43v3r/chia-gigahorse/assets/166164910/47d3ec78-8c58-43b4-963a-f16748458fb8)
![08532860-f527-4586-b911-9308056c38e2](https://github.com/madMAx43v3r/chia-gigahorse/assets/166164910/ef1f399a-e2c4-4983-ba0c-15c39e209ad7)

Meet this problem , Gigahorse plot well when Chia GUI syncing (but time increase) or off - plot time has been about 2-3 minutes. 
But when chia Gui synced always error -  Failed to allocate MEM_TYPE_DEVICE : CUDA error 2 : out of memory

I have 256gb of RAM , tried plot with two GPU,s , tried to use -M 0 and many different , Tried limit RAM usage but not been lucky because no understand how its working like. 

In windows i run Chia GUI and plotting at same time without problems but not in UBUNTU, in windows plotting time increase 7x longer but its working  , I have two 3080 ti GPU,s .

Any idea how to get this to work? Any formula ? Settings?

**Comment by madMAx43v3r** [comment]
It's means out of VRAM, not system RAM. Need to limit farmer to use second GPU and first one for plotting.

**Comment by DMJ777** [comment]
Thank you for your reply , important question , how and where to do this? any manual? Thanks a lot in advantage

**Comment by spleen911** [comment]
https://github.com/madMAx43v3r/chia-gigahorse/blob/master/chiapos/README.md#limit-gpu-usage

**Comment by spleen911** [comment]
add to plotter ........... -g 0
add to farmer startup  .......... import CUDA_VISIBLE_DEVICES=1

**Comment by DMJ777** [comment]
> add to plotter ........... -g 0 add to farmer startup .......... import CUDA_VISIBLE_DEVICES=1

-g 0 its number of one gpu ? ad this record to start code?

thank you for your reply, ho to ad to farmer this? as its start from software in ubuntu

**Comment by madMAx43v3r** [comment]
> thank you for your reply, how to ad to farmer this? as its start from software shortcut in ubuntu

Need to edit / create `~/.profile` with:

```
export CUDA_VISIBLE_DEVICES=1
```

**Comment by DMJ777** [comment]
> > thank you for your reply, how to ad to farmer this? as its start from software shortcut in ubuntu
> 
> Need to edit / create `~/.profile` with:
> 
> ```
> export CUDA_VISIBLE_DEVICES=1
> ```
> 
> And then logout / login again, or reboot.

Thank you very much , Its working 8))) Will be helpful for others ....

![plotter -g 0](https://github.com/madMAx43v3r/chia-gigahorse/assets/166164910/047ada88-0e8a-49c0-9ee1-16329c2b8b2e)
![profile edit](https://github.com/madMAx43v3r/chia-gigahorse/assets/166164910/ffc81f0b-70ee-4eb0-82a8-3ab474833fe6)
