### ISSUE TITLE
Questions about max farm size

### ISSUE THREAD

**Issue by eliliam** [madMAx43v3r/chia-gigahorse#306]
I am trying to determine the correct level of compression to use for my farm given my space available by following the [Farming Benchmark](https://github.com/madMAx43v3r/chia-gigahorse/tree/master/chiapos#farming-benchmark) section of the Chiapos readme, however I have some questions. The equation mentioned for this calculation is:
```
max_farm_size_TiB = (plot_size_GiB / 1024) * plot_filter * 8 * 1000 / total_lookup_time_seconds;
```

My first question is about the `plot_size_GiB` variable there. Is this supposed to be the effective size of a compressed plot or the real size on disk? If I have a C30 plot that has a size on disk of 44GiB, would that be the value to use in this case?

Here are the values I used:
`plot_size_GiB`: 43.31 GiB (size of a C30 plot on my disk)
`plot_filter`: 512 (current filter size)
`total_lookup_time_seconds`: 1555 seconds (Total time taken to run `./ProofOfSpace farm -r 24 --diff 75 -f /path/to/C30.plot` benchmark script against a C30 plot on my SSD, however it was a bit confusing as there is no log indicating the total runtime in the output of the command, I instead had to use the time as measured by my zsh shell)

Using these values, here is my equation after benchmarking a C30 plot:
```
(43.31 / 1024) * 512 * 8 * 1000 / 1555 = ~111
```
And here is my equation using values for a C18 plot:
```
(59.65/1024) * 512 * 8 * 1000 / 390 = ~611
```

Does this mean that my farm can support 111 TiB of compressed C30 plots? This part confuses me as well, as currently I have ~208TiB of C18 plots currently, farming off of a Tesla P4 which is being under-utilized. Would this mean that if I used only C30 plots I can only farm up to 111 TiB of plots(and if I used C18 I would be able to farm up to 611 TiB of plots)? If that is the case, how can I best find the highest compression level to use given my GPU and available space in order to fully utilize both?

**Comment by madMAx43v3r** [comment]
Your results look correct, but `ProofOfSpace` no does this calculation for you, it outputs the max farm size for plot filter 512, 256 and 128.

If you don't plan to upgrade GPU then it doesn't make sense to replot to GH 3.0, even C29 will be too much for that P4 with the coming filter 256.

**Comment by eliliam** [comment]
@madMAx43v3r thank you for your reply, I'll have to reevaluate my plan for scaling then.
