### ISSUE TITLE
Every Single Compressed Plot Failed to Open

### ISSUE THREAD

**Issue by 1Loaf-of-Bread** [madMAx43v3r/chia-gigahorse#32]
Hey, so I just recently tried out the new compressed plotting, and it doesn't seem to be going so well. I crafted around 497 plots in about 2 days with compression level 7. I craft all the plots on a physical HDD, mine are 20tb ones.

Afterwords I went and hooked up the enclosure to my farming system, and every single one of the 497 plots have failed to open.

The error displayed using the 'chia plots check' command is:

```
chia.plotting.manager            : ERROR    Failed to open file E:\plot-k32-c7-2023-02-26-16-58-16b39f2982ed05bed9e4d30f8c3fdcda32d69be8bdde28878f7325d307119d71.plot. Invalid plot file format Traceback (most recent call last):
  File "chia\plotting\manager.py", line 274, in process_file
ValueError: Invalid plot file format
```

I tried restarting the enclosure, plugging the HDD with sata directly to my mobo, restarting the chia blockchain on my system, restarting the system, and renaming to *.temp then back to *.plot, none of these have worked.

I have done this method for all my other plots using the regular CPU plotting and it has always worked.

**Comment by madMAx43v3r** [comment]
You're not using the Gigahorse harvester, double check everything.

**Comment by 1Loaf-of-Bread** [comment]
ah okay this would make sense, how would I go about transferring everything from my chia blockchain gui to the gigahorse one?

**Comment by 1Loaf-of-Bread** [comment]
`ImportError: LoadLibraryExW 'C:\Users\chiafm~1\Desktop\CHIA-G~1\blspy.pyd' failed: The specified module could not be found.`

I get this error when I try to run the farmer, harvester, and node.

**Comment by 1Loaf-of-Bread** [comment]
I download the chia-gigahorse-farmer, but whenever I use the command `chia start farmer` it gives me:

`chia_harvester: chia_harvester failed to start. Error: start failed
chia_farmer: chia_farmer failed to start. Error: start failed
chia_full_node: chia_full_node failed to start. Error: start failed
chia_wallet: chia_wallet failed to start. Error: start failed`

**Comment by 1Loaf-of-Bread** [comment]
I deleted the original folder and downloaded another one for it to just randomly start after 3 tries XD

I thank you very much for you help, I greatly appreciate it!
