### ISSUE TITLE
Plots showing as active and farming on the gigahorse-farmer, but not the pool.

### ISSUE THREAD

**Issue by 1Loaf-of-Bread** [madMAx43v3r/chia-gigahorse#33]
Hey, so after i got all of my 497 compressed plots ready for pooling, I noticed something strange. All of the plots passed validation and were being noticed by the farmer, but I was getting no points and the pool was showing nothing for my launcher id. I checked and made sure that all of the info/settings that were inputted were correct, and they were.

**Comment by madMAx43v3r** [comment]
Can you show `chia plotnft show`, without the addresses and IDs.

**Comment by 1Loaf-of-Bread** [comment]
Hey, so I found out that the most probable cause was my farming system was not strong enough to farm C7 plots. 

My plotting system is:
RAM - Corsair Vengeance 128GB @ 3200MHz
CPU - AMD Ryzen 7 5800X @ 4.6GHz
GPU - Gigabyte RTX 3090

My farming system is:
RAM - Corsair Vengeance 16GB  3200MHz
CPU - Intel i7-6700
GPU - NVIDIA Geforce GT 710

First off, thank you very much for how supportive and quick you are for getting back to us with all the help. Would I be correct that C7 plots are too difficult for my farming system to handle? Which compression level do you think would be best for my farming system? Thank you.

**Comment by madMAx43v3r** [comment]
Deleting wallet DB and letting it resync could solve this issue. Only the wallet DB, not blockchain DB.

GT 710 is not supported. C7 is too high for CPU, should use C6 or C5.
