### ISSUE TITLE
cuda error 700

### ISSUE THREAD

**Issue by B1gCarr0t** [madMAx43v3r/chia-gigahorse#331]
When I use the `cuda_plot_k32_v3` to plot C29, I get a `cuda error 700` prompt
ubuntu22.04.4 TLS
2297v2*2
1080ti 
128g ram

**Comment by madMAx43v3r** [comment]
Immediately and every time?

**Comment by madMAx43v3r** [comment]
what does `nvidia-smi` show?

**Comment by B1gCarr0t** [comment]
> what does `nvidia-smi` show?

I replaced 320g RAM.(-M 300)

This error prompt never appears again.
