### ISSUE TITLE
Chia_Recompute_Server crashing on nvdxgdmal64.dll when using OpenCL

### ISSUE THREAD

**Issue by AtomicInternet2** [madMAx43v3r/chia-gigahorse#336]
I have two 5700G CPUs serving my Gigahorse farmer each with a chia_recompute_server to access the OpenCL iGPU resources.
One of these machines also has an nVidia 1030 serving an official Chia client.

The 5700G with no nVidia GPU has a recompute server working fine.
The 5700G with the 1030 has a recompute server that runs for a few seconds and then crashes with an nVidia driver error.

I previously used CHIAPOS_VISIBLE_DEVICES=5 to force the recompute to ignore the CUDA card entirely, and have recently added the CHIAPOS_MAX_CUDA_DEVICES=0 but it still crashes on nVidia driver issues, despite telling it to only look at OpenCL.

**The command line crash is below:**

`C:\Status>SET CHIAPOS_MAX_CUDA_DEVICES=0`

`C:\Status>SET CUDA_VISIBLE_DEVICES=5`

`C:\Status>chia_recompute_server.exe`
`[chiapos] Using 16 / 16 CPU threads`
`[chiapos] Using 0 / 0 CUDA devices`
`[chiapos] Using 1 / 1 OpenCL devices (AMD Accelerated Parallel Processing)`
`Using 16 / 16 CPU threads`
`Using gfx90c (AMD Accelerated Parallel Processing)`
`ReComputeServer listening on 0.0.0.0 port 11989`

`C:\Status>`

**The Event Viewer error is below:**

`Faulting application name: chia_recompute_server.exe, version: 0.0.0.0, time stamp: 0x6677c753`
`Faulting module name: nvdxgdmal64.dll_unloaded, version: 0.0.0.0, time stamp: 0x665ba50a`
`Exception code: 0xc0000005`
`Fault offset: 0x0000000000008080`
`Faulting process id: 0x0x268C`
`Faulting application start time: 0x0x1DAC630BA0E46F8`
`Faulting application path: C:\Status\chia_recompute_server.exe`
`Faulting module path: nvdxgdmal64.dll`
`Report Id: 150f027b-4a72-48c4-a6c1-3f7362854be2`
`Faulting package full name: `
`Faulting package-relative application ID: `

**Comment by AtomicInternet2** [comment]
Figured out my system drive was dying, so that file was actually corrupt.  I've restored from backup and am running with no issues, so closing this.

**Comment by zzh-nobug** [comment]
Where did you find nvdxgdmal64.dll? I also got this error.I can't find a specific solution from your answer. Can you provide me with your solution?
