### ISSUE TITLE
couldn't create chia daemon

### ISSUE THREAD

**Issue by mikecabral** [madMAx43v3r/chia-gigahorse#346]
there's been no issues what so ever.. then all of a sudden... chia can't start...

what a piece of shit.

**Comment by Kruger1981** [comment]
That can happen if the log directory is not accessible or full.
No need to be cursing...
You say you are a dev... my 4 year old could sort that out by looking at the logs..

**Comment by mikecabral** [comment]
funny how things change after a windows update, isn't it?
lol, then adhom's... if you don't curse, you're not human.

**Comment by Kruger1981** [comment]
Tem calma caralho, Portugal ganhou.
Pior das hipoteses come um pastelinho de natal, se nao houver ai eu mando um de Albufeira.

**Comment by mikecabral** [comment]
guess you better call your 4 year old over here to fix it... much more complicated than looking at a log then giving a stupid comment.
