### ISSUE TITLE
Invalid -r | --ndevices, not enough devices: 0

### ISSUE THREAD

**Issue by heichwald** [madMAx43v3r/chia-gigahorse#4]
Hello,

I wanted to get some advice on driver issue maybe?
I am running on Ubuntu 22 with 128GB of ram, running a GTX 1070
```
~/chia-gigahorse-master/cuda-plotter/linux/x86_64$ ./cuda_plot_k32 -n 3 -C 7 -t /media/plotter/nvme2/temp -2 /media/plotter/nvme0/temp -d /media/plotter/exos12tb11/plots/compressed -d /media/plotter//exos12tb31/plots/compressed -d /media/plotter/exos12tb81/plots/compressed -c <key_c> -f <key_f>

Invalid -r | --ndevices, not enough devices: 0
```

This is the driver I use.
![Screenshot from 2023-02-10 13-08-02](https://user-images.githubusercontent.com/3836175/218165158-68525b7d-b53b-4eda-904f-7acc43942ab1.png)

CPU is intel 13600k, so with integrated graphic but i tried `-g 0 or -g 1 or -g 2` but does not change anything.

Would you know where this could be coming from?

**Comment by heichwald** [comment]
My bad, I think i did not install Cuda

**Comment by heichwald** [comment]
Reopening because still not sure what to install, I install cuda and now have:
```
which nvcc
/usr/bin/nvcc
```

but still same error

**Comment by madMAx43v3r** [comment]
need to install nvidia driver:
![image](https://user-images.githubusercontent.com/951738/218192944-f75516e6-427f-438a-9a24-102e63e792fd.png)

![image](https://user-images.githubusercontent.com/951738/218192883-c693f9ab-6819-4baf-94f4-bd9f1680d90e.png)

**Comment by madMAx43v3r** [comment]
what does `nvidia-smi` say?

**Comment by madMAx43v3r** [comment]
might have to reboot as well

**Comment by heichwald** [comment]
Thanks

Actually while the nvidia driver were installed , this command failed.

I had to disable the secure boot in the bios and then it worked.

Thanks!
