### ISSUE TITLE
cuda-plotter instance quits unexpected

### ISSUE THREAD

**Issue by NFSaga** [madMAx43v3r/chia-gigahorse#41]
cuda-plotter instance quits unexpectedly and the terminal window in which the command was initiated closes automatically very often on my linux plotting machine. I am using cuda_plot_k33 and 1/2 Partial RAM model. This generally happens towards the end of P3 or while the finished plot is being copied to the destination hard drive. It seems setting -n to -1 or any number larger than 1 almost always causes this problem while setting -n to 1 does not, although I noticed the following message while running the cuda-plotter: WritePark(): ans_length (846) > max_ans_length (845) (y = 1, i = 7899).
The linux plotting machine has an Intel Core-i9 10980XE CPU, 256 GB DDR4 RAM, 2x NVIDIA RTX A6000 (only one GPU is used for plotting), 2x NVIDIA Titan V. -2 is RAID 0 of 2x Optane 905p.
Any suggestions to fix this issue? Thanks a lot!

**Comment by aramod** [comment]
I have the same problem and I solved it with putty(SSH) terminal connection via another machine and running cuda-plotter

**Comment by madMAx43v3r** [comment]
> WritePark(): ans_length (846) > max_ans_length (845) (y = 1, i = 7899)

This is normal to happen sometimes

**Comment by madMAx43v3r** [comment]
Maybe running out of RAM?

**Comment by NFSaga** [comment]
It turns out to be an improperly configured mdadm RAID 0 of the two Optane 905p. Now it is working perfectly.
