### ISSUE TITLE
Chia wallet show don't look in root-path

### ISSUE THREAD

**Issue by azowarg** [madMAx43v3r/chia-gigahorse#53]
Hello. I install the node to run with compressed plots. I migrate  .chia and  .chia_folders from another node and place them **not** in the home directory. 
I set --root-path and --keys-root-path but it seems binary still tries to use the home directory.
`/home/yan/chia-gigahorse-farmer/chia.bin --root-path /mnt/nvme/.chia/mainnet --keys-root-path /mnt/nvme/.chia_keys/`

```
can't find /home/yan/.chia/mainnet/config/config.yaml
** please run `chia init` to migrate or create new config files **
Exception ignored in: <compiled_async_generator object get_any_service_client at 0x564681e24ff0>
Traceback (most recent call last):
  File "/home/yan/chia-gigahorse-farmer/asyncio/base_events.py", line 511, in _asyncgen_finalizer_hook
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_asyncgens'
```
But most of the other's commands work as well with new path.
`/home/yan/chia-gigahorse-farmer/chia.bin --root-path /mnt/nvme/.chia/mainnet --keys-root-path /mnt/nvme/.chia_keys/ start farmer`
```
chia_harvester: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
```

**Comment by madMAx43v3r** [comment]
Does that work with official chia version?
