### ISSUE TITLE
WritePark(): ans_length (865) > max_ans_length (858) (y = 0, i = 126)

### ISSUE THREAD

**Issue by Mathis436** [madMAx43v3r/chia-gigahorse#54]
I have received this message during plotting a couple of times on 2 different setups. 
WritePark(): ans_length (865) > max_ans_length (858) (y = 0, i = 126) 
The numbers may differ slightly but always the same error type

1st setup is a Proxmox server with a Linux server 22.04 VM & Nvidia Quadro M5000 w/ 8GB Vram
2nd is a bare metal install of Linux Desktop 22.04 & 2x Nvidia Quadro P2000 w/ 5GB Vram (-S 2) for stream setting.

Is this error harmless or is the plot that was being created no good?

Thanks

**Comment by madMAx43v3r** [comment]
Yes it can happen sometimes, nothing to worry about, unless you get like 100 or 1000 per plot.

**Comment by Mathis436** [comment]
Thanks you for the quick responce!
