### ISSUE TITLE
Incorrect Gigahorse farmer version number

### ISSUE THREAD

**Issue by Nightbeem** [madMAx43v3r/chia-gigahorse#60]
Hi.  According to Github, the latest version of the Node/Farmer is 1.6.2.giga7.  I installed the version from this link:

https://github.com/madMAx43v3r/chia-gigahorse/releases/download/v1.6.2.giga7/chia-gigahorse-farmer-1.6.2.giga7-x86_64.tar.gz

Running "./chia.bin version" gives me "1.6.2.giga5" instead of "1.6.2.giga7".  Is this expected?

**Comment by madMAx43v3r** [comment]
Yeah I forgot to update it... dont worry about it
