### ISSUE TITLE
Multiple -t problem

### ISSUE THREAD

**Issue by Xeon322** [madMAx43v3r/chia-gigahorse#63]
When i'm using multiple -t, when the thirds plot starts crafting, the second plot it's copied from the second -t to the first -t, and so on.

The command: ~/Desktop/chia-gigahorse-master/cuda-plotter/linux/x86_64/cuda_plot_k33 -C 7 -n -1 -c -f -t /media/plot/samsung/ -t /media/plot/nvme1/ -t /media/plot/raid_mare1/ -t /media/plot/raid_mare2/ -t /media/plot/raid_mare3/ -t /media/plot/raid_mare4/ -t /media/plot/raid_mare5/ -t /media/plot/raid_mic1/ -t /media/plot/raid_mic2/ -t /media/plot/raid_mic3/ 2>&1 | tee -a gigahorse.log

Crafting plot 3 out of -1 (2023/03/19 09:39:58)
Process ID: 6895
Pool Puzzle Hash:  
Farmer Public Key: 
Working Directory:   /media/plot/raid_mare1/
Working Directory 2: @RAM
Compression Level: C7 (xbits = 9, final table = 4)
Plot Name: plot-k33-c7-2023-03-19-09-39-efffc7a6fa4d7e07f2280b275ee0f133a5f8a95451878e590f5ed90eda4a4b82
[P1] Setup took 1.279 sec
[P1] Table 1 took 11.832 sec, 8589934592 entries, 16788986 max, 33570 tmp, 0 GB/s up, 6.84592 GB/s down
[P1] Table 2 took 18.787 sec, 8589765378 entries, 16789411 max, 33614 tmp, 3.83244 GB/s up, 6.22776 GB/s down
Flushing to disk took 60.762 sec
Started copy to /media/plot/samsung/plot-k33-c7-2023-03-19-09-34-1bd4030b6b836934d60e167ea725ddc5118713e37843b070bfa3e81b7653bce9.plot
[P1] Table 3 took 30.442 sec, 8589327480 entries, 16787924 max, 33676 tmp, 3.41627 GB/s up, 6.20856 GB/s down
[P1] Table 4 took 43.803 sec, 8588420527 entries, 16788404 max, 33641 tmp, 3.83508 GB/s up, 6.16398 GB/s down

**Comment by madMAx43v3r** [comment]
You didn't specify any final dir with `-d`, by default it will copy to first `-t`.

**Comment by thecybo** [comment]
> by default it will copy to first -t
Seems to work fine for me without specifying any -d

**Comment by madMAx43v3r** [comment]
`-t` has no logic for load balancing, if one `-t` is full the plotter will pause, so you should use `-d`

**Comment by thecybo** [comment]
Yeah, in the meantime I checked the logs and it seems, as OP reported, to always copy back to the first -t as a final destination. Skipped the prpblem by adding all my final disk destinations as -d instead of syncing them with 3rd party scripts
