### ISSUE TITLE
Why the 3090 is slow than 3080 in Phase 3?

### ISSUE THREAD

**Issue by sxwailyc** [madMAx43v3r/chia-gigahorse#75]
i hav two machine, one is tyan S8030(PCIE4.0) + Epyc7302 + 3090 + DDR4 2400
another is tyan S8030(PCIE4.0) + Epyc7302 + 3080 + DDR4 2666

and in phase 3, the 3090 is slow than 3080

3080
![3080](https://user-images.githubusercontent.com/13062433/229551817-20175d7b-1d03-4135-9e55-f495341b9f7d.png)

3090
![3090](https://user-images.githubusercontent.com/13062433/229551922-ef9518c1-5896-4613-80bf-d28a4eb3c9f1.png)

**Comment by ddubick** [comment]
Right from the README:  
> On PCIe 4.0 systems RAM bandwidth will be the bottleneck when paired with a bigger GPU.  To make good use of an RTX 3090 you'll need PCIe 4.0 together with 256G of quad-channel DDR4-3200 memory (or better).

So it's your ram that's the bottleneck with these faster GPUs so the rig with the DDR4 2666 is going to perform better over the one with 2400.

**Comment by sxwailyc** [comment]
> Right from the README:
> 
> > On PCIe 4.0 systems RAM bandwidth will be the bottleneck when paired with a bigger GPU.  To make good use of an RTX 3090 you'll need PCIe 4.0 together with 256G of quad-channel DDR4-3200 memory (or better).
> 
> So it's your ram that's the bottleneck with these faster GPUs so the rig with the DDR4 2666 is going to perform better over the one with 2400.

i got it, thks
