### ISSUE TITLE
Small clarification on farm size

### ISSUE THREAD

**Issue by heichwald** [madMAx43v3r/chia-gigahorse#8]
Just a small suggestion for the readme for the max farm size estimator. Could you just add a small line to confirm how to calculate the size of the farm to be compared with the max size.
Let's say you have c7 and 100 hundred plots. Is farm size in TB, 75 * 100 / 1024 or /1000 (just wanted to confirm we take compressed plots size and not uncompressed)

**Comment by madMAx43v3r** [comment]
the formula gives you TiB, the chart is for PiB, so divide the TiB by 1024 to get PiB

**Comment by heichwald** [comment]
Thanks, question was more to calculate my current farm size in TB (to compare with max from formula,). Should I just do compressed size of plot (like 75 if I use c7) * number of plots / 1024.  Just wanted to confirm I take compressed size (and not the uncompressed size) and 1024 and not 1000 to go from gb to tb

**Comment by madMAx43v3r** [comment]
your current farm size would be the total capacity of your current set of HDDs right? not sure if I follow...

to get from TiB to PiB you divide by 1024.

**Comment by heichwald** [comment]
Yes that works too. Just wanted to confirm that there was no trick relative to compressed/uncompressed. So one full 18tb hdd of compressed plots will account for 18tb for the farm size. Seems obvious but just wanted to double check.

**Comment by madMAx43v3r** [comment]
yeah I understand what you mean now, the chart is for physical farm size yes, not effective
