### ISSUE TITLE
Cuda Plotter Crashes During P1

### ISSUE THREAD

**Issue by THESHULK** [madMAx43v3r/chia-gigahorse#9]
I'm having trouble getting the k32 cuda plotter working. As you can see from the command output below, it stops plotting after P1 Table 2 without any indication as to why. Is there a log file somewhere I can look at? I'm hoping this is simply user error. I've tried various memory levels to no avail. My E: drive is an M.2 NVMe 1TB drive and the F: drive is a 14TB HDD.

Here are my system specs:
- Intel Core i7-10700K 3.8 GHz 8-Core Processor
- Nvidia 3080 Ti Founders Edition
- Corsair Dominator Platinum RGB 32 GB (2 x 16 GB) DDR4-3200 CL16 Memory

```
C:\Users\shahe\Documents\GitHub\chia-gigahorse\cuda-plotter\windows>.\cuda_plot_k32.exe -n 1 -t E:\Chia\ -d F:\Chia\ -f a672xxx -c xch1xxx -M 8
Chia k32 next-gen CUDA plotter - 15133ec
Plot Format: mmx-v2.4
Network Port: 8444 [chia]
No. GPUs: 1
No. Streams: 4
Final Destination: F:\Chia\
Shared Memory limit: 5.7 GiB
Number of Plots: 1
Initialization took 0.169 sec
Crafting plot 1 out of 1 (2023/02/10 22:33:41)
Process ID: 7120
Pool Puzzle Hash:  f17450d617e4386c6106bdaedc8ec08c9ba8398ef12877909adc5d640a7f6b15
Farmer Public Key: a672xxx
Working Directory:   E:\Chia\
Working Directory 2: @RAM
Compression Level: C1 (xbits = 15, final table = 3)
Plot Name: plot-k32-c1-2023-02-10-22-33-4a34eda13d95ef4fd882f9be5a2bbc47be8f7b515fd4fbeb5071605ef9e6f12f
[P1] Setup took 0.357 sec
[P1] Table 1 took 48.173 sec, 4294967296 entries, 16790172 max, 66650 tmp, 0 GB/s up, 0.705795 GB/s down
[P1] Table 2 took 447.948 sec, 4294838426 entries, 16785595 max, 66679 tmp, 0.0714369 GB/s up, 0.113853 GB/s down

C:\Users\shahe\Documents\GitHub\chia-gigahorse\cuda-plotter\windows>
```

**Comment by Jacek-ghub** [comment]
That CPU is PCIe 3 only, so 3080 is mostly going to sit idle.

Don't you need 128 GB RAM to use cuda plotter?

**Comment by THESHULK** [comment]
> That CPU is PCIe 3 only, so 3080 is mostly going to sit idle. 3060 ti is the cutoff for PCIe 3, I think.
> 
> Don't you need 128 GB RAM to use cuda plotter?

From what I understand, I can still plot with the 3080 Ti but I don't get any added benefits over a 3060 Ti. As for the RAM, according to this table k32 with compression level 1 the RAM is not applicable? I'm not sure what that means though.

![image](https://user-images.githubusercontent.com/53193971/218281972-e89254b2-55da-48c2-b650-90df1b5f6915.png)

**Comment by Jacek-ghub** [comment]
If you have a spare 3080, by all means, it will work great.  Not sure, but may have some power saving, as it will be underutilized.

Yup, exactly that is the farming table.  Here is the readme for cuda plotter - https://github.com/madMAx43v3r/chia-gigahorse/tree/master/cuda-plotter

**Comment by THESHULK** [comment]
Ah thank you. It's working with k29. Plots are generating in under a minute. Hopefully they're valid.

**Comment by Jacek-ghub** [comment]
Sorry, I was thinking about k32 plots.

No, k29 are no good.  Only used to for testing.

If you plot for Chia, you need k32.  If for MMX, the minimum is k30.

**Comment by THESHULK** [comment]
I see, well that's a bummer. So I need a minimum of 128GB RAM so I can plot k32. And once I create the plots, I have to farm them with the gigahorse node, right?

**Comment by madMAx43v3r** [comment]
yes

**Comment by THESHULK** [comment]
Thanks so much!

**Comment by Jacek-ghub** [comment]
> I see, well that's a bummer. So I need a minimum of 128GB RAM so I can plot k32.

However, you can open an enhancement ticket asking for 64 GB RAM for k32 plots, and have your buddies support you on that. ;)  There is a lot of chat about that as most farmers don't run server grade boxes.
